@startuml hurtownia

entity Date {
    *id: Id
    --
    *date: Date
    *weekday: Enum("monday","tuesday","wednesday","thursday","friday","staturday","sunday")
    *weekend: Bool
    *quarter: Enum("I","II","III","IV")
    *year: Int
}

entity CustomerType {
    *id: Id
    --
    *ageGroup: Enum("0-13", "14-18", "18-30", "30-39", "40-49", "50-64", "65-79", "80-")
    *yearsAsCustomer: Enum("0-1", "1-2", "3-4", "5-7", "8-10","11-")
    *name: Varchar
    *city: Varchar
    *country: ISOCountryCode
}

entity Transaction {
    *id: Id
    --
    *type: Enum("digital","stream","e-shop","shop")
    *provider: Enum("mastercard","visa","paypal","payu")
    *customerIpFistOctet: Int
}

entity StreamingService {
    *id: Id
    --
    *name: Varchar
    *monthsOnTheMarket: Enum("0-1","1-2","3-5","6-9","10-16","17-24","25-48","49-")
}

entity MusicLabel {
    *id: Id
    --
    *name: Varchar
    *yearsOnTheMarket: Enum("0-1", "1-3", "4-10", "11-20", "21-")
}

entity ArtistGroup {
    *id: Id
    --
    *artists: Varchar
    *count: Int
}

entity Track {
    *id: Id
    --
    *title: Varchar
    *edit: Enum("original","radio","remix","cover","preview","instrumental")
    *isrc: ISRC
    *duration: Enum("0-10","11-30","31-60","61-120","121-300","301-600","600-3600","3601-7200","7200-")
}

entity Release {
    *id: Id
    --
    *type: Enum("single","digital","stream")
    *upc: Bigint(20)
    *name: Varchar
    *originalPrice: Int
    *monthsOnTheMarket: Enum("0-1","1-2","3-5","6-9","10-16","17-24","25-48","49-")
    *tracksCount: Int
}

entity Sales {
    *id: Id
    *customerTypeId: Id
    *musicLabelId: Id
    *transactionId: Id
    *artistGroupId: Id
    *dateId: Id
    *releaseId: Id
    streamingService: Id
    --
    fromStream: Bool
    *quantity: Int
    *totalPrice: USD
}

Release "1" ||--|{ "1..n" Sales:>
MusicLabel "1" ||--|{ "1..n" Sales:>
ArtistGroup "1" ||--|{ "1..n" Sales:>
CustomerType "1" ||--|{ "1..n" Sales:>
Transaction "1" ||--|{ "1..n" Sales:>
Date "1" ||--|{ "1..n" Sales:>
StreamingService "0..1" |o--|{ "1..n" Sales:>

entity Streaming {
    *id: Id
    *customerTypeId: Id
    *artistGroupId: Id
    *trackId: Id
    *releaseId: Id
    *dateId: Id
    *musicLabelId: Id
    *streamingServiceId: Id
    --
    *duration: Int
    *quality: Enum("flac","acc-128","mp3-320","waw")
}

Streaming "1..n" }|--|| "1" CustomerType:>
Streaming "1..n" }|--|| "1" ArtistGroup:>
Streaming "1..n" }|--|| "1" Track:>
Release "1" ||--|{ "1..n" Streaming:>
Date "1" ||--|{ "1..n" Streaming:>
MusicLabel "1" ||--|{ "1..n" Streaming:>
StreamingService "1" ||--|{ "1..n" Streaming:>

entity Popularity {
    *id: Id
    *customerTypeId: Id
    *releaseId: Id
    *dateId: Id
    *musicLabelId: Id
    artistGroupId: Id
    trackId: Id
    streamingService: Id
    --
    type: Enum["release","track"]
    *source: Enum("facebook","streaming-service","player","android-app","ios-app","other")
}

Popularity "1..n" }|--|| "1" CustomerType:>
Popularity "1..n" }|--|| "1" Release:>
Popularity "1..n" }|--|| "1" Date:>
Popularity "1..n" }|--|| "1" MusicLabel:>
Popularity "1..n" }|--o| "0..1" ArtistGroup:>
Popularity "1..n" }|--o| "0..1" Track:>
Popularity "1..n" }|--o| "0..1" StreamingService:>

@enduml