parameters:
    env(DATABASE_URL): ''
    env(WAREHOUSE_STAGE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                url: '%env(resolve:DATABASE_URL)%'
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

            warehouse_stage:
                url: '%env(resolve:WAREHOUSE_STAGE_URL)%'
                charset: utf8mb4

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            warehouse_stage:
                connection: warehouse_stage
                mappings:
                    DataWarehouseStage:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/DataWarehouseStage'
                        prefix: 'App\DataWarehouseStage'
                        alias: DataWarehouseStage
