version: "3.6"

volumes:
  mysql_data: {}
  oracle_data:
    external:
      name: oracle-main-data-volume

services:
  redis:
    image: redis:5-alpine
    ports:
      - '6379:6379'

  composer:
    env_file: .env.docker
    build:
      context: .
      target: Composer

  interactive:
    env_file: .env.docker
    build:
      context: .
      target: SymfonyConsole
    volumes:
      - .:/usr/src/app

  console:
    env_file: .env.docker
    build:
      context: .
      target: SymfonyConsole

  oradb:
    image: store/oracle/database-enterprise:12.2.0.1-slim
    ports:
      - 1521:1521
    volumes:
      - oracle_data:/ORCL

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Passw0rd
    volumes:
      - mysql_data:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=Passw0rd
    ports:
      - "8080:80"